import * as pulumi from '@pulumi/pulumi'
import * as aws from '@pulumi/aws'

export interface UploadsBucketConfig {
  environment: 'dev' | 'qa' | 'prod'
}

/**
 * Creates IaC management for the uploads.thegoodparty.org bucket.
 * This is a legacy bucket used for avatar uploads.
 *
 * Previously unmanaged - now locked down with public access blocks.
 * Access should be through signed URLs generated by the API.
 */
export function createUploadsBucket({ environment }: UploadsBucketConfig): {
  bucket: aws.s3.BucketV2
  bucketName: pulumi.Output<string>
} {
  const bucketName = 'uploads.thegoodparty.org'

  const bucket = new aws.s3.BucketV2('uploadsBucket', {
    bucket: bucketName,
    forceDestroy: false,
  })

  // Enable ALL public access blocks
  new aws.s3.BucketPublicAccessBlock('uploadsBucketPublicAccessBlock', {
    bucket: bucket.id,
    blockPublicAcls: true,
    blockPublicPolicy: true,
    ignorePublicAcls: true,
    restrictPublicBuckets: true,
  })

  // Enable server-side encryption
  new aws.s3.BucketServerSideEncryptionConfigurationV2(
    'uploadsBucketEncryption',
    {
      bucket: bucket.id,
      rules: [
        {
          applyServerSideEncryptionByDefault: {
            sseAlgorithm: 'AES256',
          },
          bucketKeyEnabled: true,
        },
      ],
    },
  )

  // CORS configuration for signed URL uploads
  new aws.s3.BucketCorsConfigurationV2('uploadsBucketCors', {
    bucket: bucket.id,
    corsRules: [
      {
        allowedHeaders: ['*'],
        allowedMethods: ['GET', 'PUT', 'POST'],
        allowedOrigins:
          environment === 'prod'
            ? ['https://goodparty.org']
            : [
                'http://localhost:4000',
                'https://dev.goodparty.org',
                'https://qa.goodparty.org',
              ],
        exposeHeaders: ['ETag'],
        maxAgeSeconds: 3000,
      },
    ],
  })

  return {
    bucket,
    bucketName: bucket.bucket,
  }
}
