export const fixedCampaigns = [
  {
    details: {
      state: 'CA',
      zip: '90001',
      ballotLevel: 'State',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-06-03',
      geoLocation: {},
      party: 'Independent',
      level: 'State',
      office: 'Governor',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Governor',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'TX',
      zip: '73301',
      ballotLevel: 'State',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-03-05',
      geoLocation: {},
      party: 'Republican',
      level: 'State',
      office: 'Senator',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Senator',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'NY',
      zip: '10001',
      ballotLevel: 'City',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-06-25',
      geoLocation: {},
      party: 'Democratic',
      level: 'City',
      office: 'Councilman',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'City Council',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'FL',
      zip: '33101',
      ballotLevel: 'City',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-08-20',
      geoLocation: {},
      party: 'Independent',
      level: 'City',
      office: 'Mayor',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Mayor',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'OH',
      zip: '44101',
      ballotLevel: 'County',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-05-07',
      geoLocation: {},
      party: 'Republican',
      level: 'County',
      office: 'Sheriff',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Sheriff',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'IL',
      zip: '60601',
      ballotLevel: 'State',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-03-19',
      geoLocation: {},
      party: 'Democratic',
      level: 'State',
      office: 'Governor',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Governor',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'PA',
      zip: '19101',
      ballotLevel: 'County',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-04-23',
      geoLocation: {},
      party: 'Independent',
      level: 'County',
      office: 'Commissioner',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Commissioner',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'AZ',
      zip: '85001',
      ballotLevel: 'State',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-08-27',
      geoLocation: {},
      party: 'Republican',
      level: 'State',
      office: 'Attorney General',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Attorney General',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'MI',
      zip: '48201',
      ballotLevel: 'County',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-05-07',
      geoLocation: {},
      party: 'Independent',
      level: 'County',
      office: 'Treasurer',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'Treasurer',
      },
    },
    didWin: true,
    isDemo: false,
  },
  {
    details: {
      state: 'GA',
      zip: '30301',
      ballotLevel: 'City',
      electionDate: '2024-11-05',
      primaryElectionDate: '2024-07-23',
      geoLocation: {},
      party: 'Democratic',
      level: 'City',
      office: 'Councilman',
    },
    data: {
      hubSpotUpdates: {
        election_results: 'Won General',
        verified_candidates: 'Yes',
        office_type: 'City Council',
      },
    },
    didWin: true,
    isDemo: false,
  },
]
