import { BallotReadyPositionLevel } from '@/campaigns/campaigns.types'
import { BallotReadyRaceFixture } from '@e2e-tests/generateBallotReadyRaceFixtures'
// IMPORTANT: If you wish to edit this file, edit generateBallotReadyRaceFixtures.ts instead

// This is real BallotReady data, for use in tests that depend on real data
// You can expand what fields this provides from Race, Position, Election, etc.,
// by expanding the associated Databricks query and re-generating the fixtures via npm run fixtures:ballotready-races
export const BallotReadyRaceFixtures = [
  {
    state: 'AK',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDI1MDgx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTg4Mg==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNDg4ODU=',
    ballotLevel: BallotReadyPositionLevel.STATE,
    otherOffice: 'Alaska House of Representatives - District 2',
    electionDate: '2026-11-03',
  },
  {
    state: 'AK',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjA4NDkx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjE4OQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vOTA5NTY=',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Bering Strait REAA 12 School Board - Section 1, Seat B',
    electionDate: '2026-10-06',
  },
  {
    state: 'AL',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDYwMDg0',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjA3Ng==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTI4ODg1',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Cleburne County Commission - District 2',
    electionDate: '2026-06-23',
  },
  {
    state: 'AL',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjE3MTQx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjAyNg==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTI5Mzk2',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Fayette County School Board - District 4',
    electionDate: '2026-05-26',
  },
  {
    state: 'AR',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDk1NzU3',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjA3Nw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTMwMDE1',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Conway County Justice of the Peace - District 9',
    electionDate: '2026-06-16',
  },
  {
    state: 'AR',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDk4NTI5',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjAyNw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTMxMTQx',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'St. Francis County Sheriff/Collector',
    electionDate: '2026-05-19',
  },
  {
    state: 'AZ',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDI1MjM0',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjAyOA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNDg5NTk=',
    ballotLevel: BallotReadyPositionLevel.STATE,
    otherOffice: 'Arizona House of Representatives - District 26',
    electionDate: '2026-08-04',
  },
  {
    state: 'AZ',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjI4MDUw',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk3Mg==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTc5NzYz',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Eloy City Council',
    electionDate: '2026-11-03',
  },
  {
    state: 'CA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDcyNzQ2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjAyOQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTU1ODA4',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Plumas County Treasurer/Tax Collector',
    electionDate: '2026-06-02',
  },
  {
    state: 'CA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjM4MDg2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk3Mw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjE5NTAw',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Yucca Valley Town Council - District 3',
    electionDate: '2026-11-03',
  },
  {
    state: 'CO',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDUxMjk5',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjAzMA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vOTc3NjY=',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Conejos County Treasurer',
    electionDate: '2026-06-30',
  },
  {
    state: 'CO',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNDA5ODI4',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjUyMA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjMwNjc2',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Denver City Council - District 10',
    electionDate: '2027-06-01',
  },
  {
    state: 'CT',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNDUxMjA1',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjQ5Nw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTc0NzM0',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Derby School Board',
    electionDate: '2027-11-02',
  },
  {
    state: 'CT',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNDYzNDM3',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjUyMg==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjI4MDQ1',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Torrington City Public Safety Board',
    electionDate: '2027-09-14',
  },
  {
    state: 'DC',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDM5MzY2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk3NQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNTM2MDQ=',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice:
      'District of Columbia Advisory Neighborhood Commission - District 1A10',
    electionDate: '2026-11-03',
  },
  {
    state: 'DC',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDM5NjEz',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk3NQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNTM4Nzg=',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice:
      'District of Columbia Advisory Neighborhood Commission - District 8D02',
    electionDate: '2026-11-03',
  },
  {
    state: 'DE',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yODMyOTE3',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNzcxOQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNTkwNTI=',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Colonial School Board - District F',
    electionDate: '2026-05-12',
  },
  {
    state: 'DE',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yODMzMDAx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNzcxNw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjc0NDMx',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Georgetown Town Council - Ward 4',
    electionDate: '2026-05-09',
  },
  {
    state: 'FL',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjUzNzAy',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjE3OA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMzgzMTIz',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Jupiter Inlet Colony Town Mayor',
    electionDate: '2026-03-10',
  },
  {
    state: 'FL',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yODk4MTQx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjY4OQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjkxMzIy',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'South Bay City Commission - Seat 5',
    electionDate: '2027-03-09',
  },
  {
    state: 'GA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjI1ODAx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk3OA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTY4MTMw',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Putnam County School Board - District 2',
    electionDate: '2026-11-03',
  },
  {
    state: 'GA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjI1OTM4',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjAzNQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTY4MzQ4',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Savannah-Chatham County School Board - At Large',
    electionDate: '2026-05-19',
  },
  {
    state: 'HI',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDI3MzU2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk3OQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNDk3OTI=',
    ballotLevel: BallotReadyPositionLevel.STATE,
    otherOffice: 'Hawaii House of Representatives - District 21',
    electionDate: '2026-11-03',
  },
  {
    state: 'HI',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDIxNjIz',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjAzNg==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNDYzNzY=',
    ballotLevel: BallotReadyPositionLevel.FEDERAL,
    otherOffice:
      'U.S. House of Representatives - Hawaii 2nd Congressional District',
    electionDate: '2026-08-08',
  },
  {
    state: 'IA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjMwNjc2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4MA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTg3NjYw',
    ballotLevel: BallotReadyPositionLevel.TOWNSHIP,
    otherOffice: 'Scott County: Lincoln Township Clerk',
    electionDate: '2026-11-03',
  },
  {
    state: 'IA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNDcxNTcx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjU0OA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjQzMDk0',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Thompson City Mayor',
    electionDate: '2027-11-30',
  },
  {
    state: 'ID',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDM5ODEz',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4MQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNTk3MzU=',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Jefferson County Council - District 1',
    electionDate: '2026-11-03',
  },
  {
    state: 'ID',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDM5OTEw',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4MQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNTk4MjY=',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Valley County Assessor',
    electionDate: '2026-11-03',
  },
  {
    state: 'IL',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNTE5OTg5',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjUxNQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMzYzNjE0',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Kinsman Village Mayor',
    electionDate: '2027-04-06',
  },
  {
    state: 'IL',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNTI1NjIx',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjUxNQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMzg3ODA5',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Blandinsville Park District Board',
    electionDate: '2027-04-06',
  },
  {
    state: 'IN',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjAyNjcy',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjA0MA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNzI2OTk=',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Kewanna Town Clerk/Treasurer',
    electionDate: '2026-05-05',
  },
  {
    state: 'IN',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNDYwNzg3',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjQ5OQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjA4NDM5',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Griffith Town Council - Ward 4',
    electionDate: '2027-11-02',
  },
  {
    state: 'KS',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjA1MTky',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjA0MQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNzYwMDM=',
    ballotLevel: BallotReadyPositionLevel.TOWNSHIP,
    otherOffice: 'Gove County: Payne Township Clerk',
    electionDate: '2026-08-04',
  },
  {
    state: 'KS',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNDQxNDQz',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjYzNA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNzc2MTI=',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Copeland USD 476 School Board',
    electionDate: '2027-08-03',
  },
  {
    state: 'KY',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDQ2NjY1',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4NQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vODYxNDU=',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Morgan County Constable - District 3',
    electionDate: '2026-11-03',
  },
  {
    state: 'KY',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjA3NjU1',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4NQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vODgxMTU=',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Caneyville City Mayor',
    electionDate: '2026-11-03',
  },
  {
    state: 'LA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjE2MTI3',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTkwNg==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTI3MDAx',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'East Carroll Parish School Board - District 5',
    electionDate: '2026-12-05',
  },
  {
    state: 'LA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNDE0MzYw',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjI1Nw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMzE4NTc0',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Jefferson Parish Court Clerk',
    electionDate: '2027-10-16',
  },
  {
    state: 'MA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDIzMzQ2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjA0Mw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNDcyODM=',
    ballotLevel: BallotReadyPositionLevel.STATE,
    otherOffice:
      'Massachusetts State Senate - Hampden and Hampshire (District 2)',
    electionDate: '2026-09-01',
  },
  {
    state: 'MA',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNzk3MDYw',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjUwMA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMzk5NDc5',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Lowell City Council - At Large',
    electionDate: '2027-11-02',
  },
  {
    state: 'MD',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDI5MDI5',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjA0NA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNTA2Mjk=',
    ballotLevel: BallotReadyPositionLevel.STATE,
    otherOffice: 'Maryland House of Delegates - District 1A',
    electionDate: '2026-06-30',
  },
  {
    state: 'MD',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDIzMjkw',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4Nw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNDcyNTQ=',
    ballotLevel: BallotReadyPositionLevel.STATE,
    otherOffice: 'Maryland State Senate - District 23',
    electionDate: '2026-11-03',
  },
  {
    state: 'ME',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDU4NDA1',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4OA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTIxNDM2',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Aroostook County Treasurer',
    electionDate: '2026-11-03',
  },
  {
    state: 'ME',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yODM0NTc3',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNzg3MA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTIyMDE5',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Maranacook Area/RSU 38 School Board - Manchester',
    electionDate: '2026-06-11',
  },
  {
    state: 'MI',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjE5NTU0',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNTk4OQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTQyODkx',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Bellevue Village President',
    electionDate: '2026-11-03',
  },
  {
    state: 'MI',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yODI2NzUy',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNzUzNA==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMzMyNzEy',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Bangor City Council',
    electionDate: '2026-05-05',
  },
  {
    state: 'MN',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMDU1ODU2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjA0Nw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTA4OTkz',
    ballotLevel: BallotReadyPositionLevel.COUNTY,
    otherOffice: 'Waseca County Sheriff',
    electionDate: '2026-08-11',
  },
  {
    state: 'MN',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNzMzOTQ2',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjc1Nw==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMjA5NzA2',
    ballotLevel: BallotReadyPositionLevel.TOWNSHIP,
    otherOffice: 'Wright County: Monticello Township Treasurer',
    electionDate: '2027-03-09',
  },
  {
    state: 'MO',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yMjI4NjY4',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjE4MQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vMTgxMzk4',
    ballotLevel: BallotReadyPositionLevel.CITY,
    otherOffice: 'Fair Grove City Council - Ward 2',
    electionDate: '2026-04-07',
  },
  {
    state: 'MO',
    raceId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb25FbGVjdGlvbi8yNTI2NTgy',
    electionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvRWxlY3Rpb24vNjU2NQ==',
    positionId: 'Z2lkOi8vYmFsbG90LWZhY3RvcnkvUG9zaXRpb24vNDEyOTE1',
    ballotLevel: BallotReadyPositionLevel.LOCAL,
    otherOffice: 'Claycomo Special Road District No. 4 Board',
    electionDate: '2027-04-06',
  },
] satisfies ReadonlyArray<BallotReadyRaceFixture>
